version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestProjectMainProject
  gitServerName: testP1
  gitUrl: https://github.com/PoojaAnandGit/TestProjectMainProject
  gitUsername: PoojaAnandGit
  gitBranch: main
- name: packagesTest1
  gitServerName: testP1
  gitUrl: https://github.com/PoojaAnandGit
  gitUsername: PoojaAnandGit
  gitBranch: main
